python crop_panorama_images.py et07-imagination-lab
python crop_panorama_images.py et12-corner-1
python crop_panorama_images.py et12-corner-2
python crop_panorama_images.py et07-cr-galgary
python crop_panorama_images.py et12-cr-hamburg
python crop_panorama_images.py et12-cr-helsinki
python crop_panorama_images.py et12-cr-hongkong
python crop_panorama_images.py et12-cr-honolulu
python crop_panorama_images.py et12-kitchen
python crop_panorama_images.py et12-office-104
python crop_panorama_images.py et12-office-108
python crop_panorama_images.py et12-office-110
python crop_panorama_images.py et12-office-111
python crop_panorama_images.py et12-office-112
python crop_panorama_images.py et12-office-113
python crop_panorama_images.py et12-office-114
python crop_panorama_images.py et12-office-115
python crop_panorama_images.py et12-office-117
python crop_panorama_images.py et12-office-132
python crop_panorama_images.py et07-office-114
python crop_panorama_images.py et07-office-419
python crop_panorama_images.py et07-office-420
python crop_panorama_images.py et07-office-423
python crop_panorama_images.py et07-office-424
