python gen_visu_h5.py et07-imagination-lab --data_dir  panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-corner-1 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-corner-2 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et07-cr-galgary --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-cr-hamburg --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-cr-helsinki --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-cr-hongkong --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-cr-honolulu --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-kitchen --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-104 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-108 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-110 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-111 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-112 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-113 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-114 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-115 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-117 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et12-office-132 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et07-office-114 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et07-office-419 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et07-office-420 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et07-office-423 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
python gen_visu_h5.py et07-office-424 --data_dir panorama_images_cropped_rgb_images_with_jitters --num_imgs_per_loc 10
