python crop_panorama_images.py et07-imagination-lab --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-corner-1 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-corner-2 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et07-cr-galgary --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-cr-hamburg --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-cr-helsinki --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-cr-hongkong --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-cr-honolulu --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-kitchen --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-104 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-108 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-110 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-111 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-112 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-113 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-114 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-115 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-117 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et12-office-132 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et07-office-114 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et07-office-419 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et07-office-420 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et07-office-423 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
python crop_panorama_images.py et07-office-424 --theta_jitter 3.0 --phi_jitter 2.0 --gaussian_noise_sigma 8.0 --number_jitter 10 --output_suffix cropped_rgb_images_with_jitters
